"use client"

import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './modules/navbar/navbar.jsx'
import Footer from './modules/footer/footer.jsx'
import { usePathname } from 'next/navigation'
// ========================================================
import { AppProvider } from "@/app/context/AppContext.jsx";
// ========================================================


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

// export const metadata = {
//   title: 'Awais',
//   description: 'Generated by Awais'
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const excludePaths = ['/login', '/signup'];

  const shouldShowNavbarAndFooter = !excludePaths.includes(pathname);

  return (
    <html lang='en'>
      <head>

        <title>Pizza Lab</title>

        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-200`}
      >
        <AppProvider>

          {/* =============================================================================== */}
          {shouldShowNavbarAndFooter && <Navbar />}
          {children}
          {shouldShowNavbarAndFooter && <Footer />}
          {/* =============================================================================== */}

        </AppProvider>
      </body>
    </html>
  )
}
